package org.csanchez.adk.agents.k8sagent.remediation;

import com.google.adk.tools.BaseTool;
import org.kohsuke.github.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;
import java.util.Map;

/**
 * Tool that creates GitHub PRs with fixes.
 * Git operations are deterministic, only the fix content comes from AI.
 */
public class GitHubPRTool extends BaseTool {
	
	private static final Logger logger = LoggerFactory.getLogger(GitHubPRTool.class);
	private final GitOperations gitOps;
	private final GitHub github;
	
	public GitHubPRTool(GitOperations gitOps) throws Exception {
		super(
			"create_github_pr",
			"Creates a GitHub pull request with code fixes. Requires: repoUrl, fileChanges (map), fixDescription, rootCause, namespace, podName"
		);
		this.gitOps = gitOps;
		String token = System.getenv("GITHUB_TOKEN");
		if (token == null || token.isEmpty()) {
			throw new IllegalStateException("GITHUB_TOKEN environment variable is required");
		}
		this.github = new GitHubBuilder().withOAuthToken(token).build();
	}
	
	public Object execute(Map<String, Object> params) {
		logger.info("=== Executing Tool: create_github_pr ===");
		
		// AI provides these (WHAT to fix):
		String repoUrl = (String) params.get("repoUrl");
		@SuppressWarnings("unchecked")
		Map<String, String> fileChanges = (Map<String, String>) params.get("fileChanges");
		String fixDescription = (String) params.get("fixDescription");
		
		if (repoUrl == null || fileChanges == null || fixDescription == null) {
			return Map.of("success", false, "error", "Missing required parameters: repoUrl, fileChanges, fixDescription");
		}
		
		logger.info("Creating PR for repository: {}", repoUrl);
		
		// Deterministic git workflow (HOW to fix):
		String branchName = "fix/k8s-issue-" + System.currentTimeMillis();
		String token = System.getenv("GITHUB_TOKEN");
		Path repoPath = null;
		
		try {
			// 1. Clone (library)
			repoPath = gitOps.cloneRepository(repoUrl, token);
			
			// 2. Create branch (library)
			gitOps.createBranch(repoPath, branchName);
			
			// 3. Apply AI-suggested changes (library file I/O)
			gitOps.applyChanges(repoPath, fileChanges);
			
			// 4. Commit and push (library)
			String commitMsg = "fix: " + fixDescription;
			gitOps.commitAndPush(repoPath, commitMsg, token);
			
			// 5. Create PR via GitHub API (library)
			String repoName = extractRepoName(repoUrl);
			GHRepository repo = github.getRepository(repoName);
			
			String baseBranch = repo.getDefaultBranch();
			String prTitle = "Fix: " + fixDescription;
			String prBody = generatePRBody(params);
			
			GHPullRequest pr = repo.createPullRequest(
				prTitle,
				branchName,
				baseBranch,
				prBody
			);
			
			logger.info("Successfully created PR: {}", pr.getHtmlUrl());
			
			return Map.of(
				"success", true,
				"prUrl", pr.getHtmlUrl().toString(),
				"prNumber", pr.getNumber(),
				"branch", branchName
			);
			
		} catch (Exception e) {
			logger.error("Failed to create PR", e);
			return Map.of(
				"success", false,
				"error", e.getMessage()
			);
		} finally {
			// Cleanup temporary directory
			if (repoPath != null) {
				gitOps.cleanup(repoPath);
			}
		}
	}
	
	/**
	 * Extract repository name from URL (e.g., "owner/repo")
	 */
	private String extractRepoName(String repoUrl) {
		// Handle formats: https://github.com/owner/repo or https://github.com/owner/repo.git
		String cleaned = repoUrl.replace("https://github.com/", "")
			.replace(".git", "");
		return cleaned;
	}
	
	/**
	 * Generate PR body with analysis results
	 */
	private String generatePRBody(Map<String, Object> params) {
		String rootCause = (String) params.getOrDefault("rootCause", "Not available");
		String fixDescription = (String) params.getOrDefault("fixDescription", "");
		String testingRecommendations = (String) params.getOrDefault("testingRecommendations", "Run existing test suite");
		String namespace = (String) params.getOrDefault("namespace", "unknown");
		String podName = (String) params.getOrDefault("podName", "unknown");
		
		@SuppressWarnings("unchecked")
		Map<String, String> fileChanges = (Map<String, String>) params.get("fileChanges");
		String changesSummary = fileChanges != null ? 
			String.join(", ", fileChanges.keySet()) : "No files changed";
		
		return String.format("""
			## Root Cause Analysis
			%s
			
			## Changes Made
			Modified files: %s
			
			%s
			
			## Testing Recommendations
			%s
			
			## Related Kubernetes Resources
			- **Namespace**: `%s`
			- **Pod**: `%s`
			
			---
			*This PR was automatically generated by Kubernetes AI Agent*
			*Review carefully before merging*
			""",
			rootCause,
			changesSummary,
			fixDescription,
			testingRecommendations,
			namespace,
			podName
		);
	}
}


